server:
  port: 8888

spring:
  application:
    name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gg
          searchPaths: micro-service-config
          username:
          password:
          
management:
  endpoints:
    web:
      exposure:
\\
