server:
  port: 8888

spring:
  application:
    name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Incarnation-p-lee/spring-cloud-example-config/
          searchPaths: micro-service-config
          username:
          password:
          
management:
  endpoints:
    web:
      exposure:
        include: *
